version: '2'
services:
  db:
    build: mysql/samoyed/
    environment:
      MYSQL_DATABASE: samoyed
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
